CREATE TABLE `CAR_DATA`(
    `id` INT NOT NULL AUTO_INCREMENT,
    `car_id` INT NOT NULL,
    `make_id` INT NOT NULL,
    `name_m` VARCHAR(255),
    `make_name` VARCHAR(255),
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)